name: Godot 4.5 Beta 5 Android Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip openjdk-11-jdk zip tar

      - name: Download Godot Linux x86_64
        run: |
          mkdir godot
          wget -q https://github.com/godotengine/godot-builds/releases/download/4.5-beta5/Godot_v4.5-beta5_linux.x86_64.zip
          unzip -q Godot_v4.5-beta5_linux.x86_64.zip -d godot
          chmod +x godot/Godot_v4.5-beta5_linux.x86_64

      - name: Download Godot export templates
        run: |
          mkdir -p ~/.local/share/godot/templates/4.5.beta5
          wget -q https://github.com/godotengine/godot-builds/releases/download/4.5-beta5/Godot_v4.5-beta5_export_templates.tpz
          unzip -q Godot_v4.5-beta5_export_templates.tpz -d ~/.local/share/godot/templates/4.5.beta5

      - name: Android SDK & NDK Setup
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/33.0.2:$PATH

          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses || true

          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "ndk;25.2.9519653"

      - name: Generate debug keystore
        run: |
          keytool -genkeypair -noprompt \
            -keystore debug.keystore \
            -storepass android \
            -alias androiddebugkey \
            -keypass android \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Godot,L=Internet,ST=World,C=US"

      - name: Create export_presets.cfg
        run: |
          cat <<EOL > export_presets.cfg
          [preset.0]
          name="Android"
          platform="Android"
          runnable=true           
          advanced_options=false
          dedicated_server=false
          custom_features=""
          export_filter="all_resources"
          include_filter=""
          exclude_filter=""
          export_path=""
          patches=PackedStringArray()
          encryption_include_filters=""
          encryption_exclude_filters=""
          seed=0
          encrypt_pck=false
          encrypt_directory=false
          script_export_mode=2

          [preset.0.options]
          custom_template/debug=""
          custom_template/release=""
          gradle_build/use_gradle_build=false
          gradle_build/gradle_build_directory=""
          gradle_build/android_source_template=""
          gradle_build/export_format=0
          gradle_build/min_sdk=""
          gradle_build/target_sdk=""
          gradle_build/custom_theme_attributes={}
          architectures/armeabi-v7a=false
          architectures/arm64-v8a=true
          architectures/x86=false
          architectures/x86_64=false
          version/code=1
          version/name=""
          package/unique_name="com.lewriner.game"
          package/name=""
          package/signed=true
          package/app_category=2
          package/retain_data_on_uninstall=false
          package/exclude_from_recents=false
          package/show_in_android_tv=false
          package/show_in_app_library=true
          package/show_as_launcher_app=false
          launcher_icons/main_192x192=""
          launcher_icons/adaptive_foreground_432x432=""
          launcher_icons/adaptive_background_432x432=""
          launcher_icons/adaptive_monochrome_432x432=""
          graphics/opengl_debug=false
          shader_baker/enabled=false
          xr_features/xr_mode=0
          gesture/swipe_to_dismiss=false
          screen/immersive_mode=true
          screen/edge_to_edge=false
          screen/support_small=true
          screen/support_normal=true
          screen/support_large=true
          screen/support_xlarge=true
          screen/background_color=Color(0, 0, 0, 1)
          user_data_backup/allow=false
          command_line/extra_args=""
          apk_expansion/enable=false
          apk_expansion/SALT=""
          apk_expansion/public_key=""
          permissions/custom_permissions=PackedStringArray()
          permissions/internet=true
          permissions/access_coarse_location=false
          permissions/access_fine_location=false
          permissions/camera=false
          permissions/record_audio=false
          permissions/wake_lock=false
          EOL

      - name: Build Android Debug APK
        run: |
          ./godot/Godot_v4.5-beta5_linux.x86_64 --headless --export "Android Debug APK" build/debug.apk --verbose

      - name: Build Android Release APK
        env:
          KEYSTORE_PASSWORD: android
          KEY_ALIAS: androiddebugkey
          KEY_PASSWORD: android
        run: |
          ./godot/Godot_v4.5-beta5_linux.x86_64 --headless --export "Android Release APK" build/release.apk --verbose

      - name: Build Android Release AAB
        env:
          KEYSTORE_PASSWORD: android
          KEY_ALIAS: androiddebugkey
          KEY_PASSWORD: android
        run: |
          ./godot/Godot_v4.5-beta5_linux.x86_64 --headless --export "Android Release AAB" build/release.aab --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: godot-android-build
          path: build/
