name: Godot 4.5 Beta 5 Android Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip openjdk-11-jdk zip tar

      - name: Download Godot Linux x86_64
        run: |
          mkdir godot
          wget -q https://github.com/godotengine/godot-builds/releases/download/4.5-beta5/Godot_v4.5-beta5_linux.x86_64.zip
          unzip -q Godot_v4.5-beta5_linux.x86_64.zip -d godot
          chmod +x godot/Godot_v4.5-beta5_linux.x86_64

      - name: Download Godot export templates
        run: |
          mkdir -p ~/.local/share/godot/templates/4.5.beta5
          wget -q https://github.com/godotengine/godot-builds/releases/download/4.5-beta5/Godot_v4.5-beta5_export_templates.tpz
          unzip -q Godot_v4.5-beta5_export_templates.tpz -d ~/.local/share/godot/templates/4.5.beta5

      - name: Android SDK & NDK Setup
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/33.0.2:$PATH

          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses || true

          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "ndk;25.2.9519653"

      - name: Generate debug keystore
        run: |
          keytool -genkeypair -noprompt \
            -keystore debug.keystore \
            -storepass android \
            -alias androiddebugkey \
            -keypass android \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Godot,L=Internet,ST=World,C=US"

      - name: Create export_presets.cfg
        run: |
          mkdir -p export_presets
          cat <<EOL > export_presets/export_presets.cfg
          [preset.1]
          name="Android"
          platform="Android"
          file="build/app-release.apk"
          keystore="debug.keystore"
          store_password="android"
          alias="androiddebugkey"
          alias_password="android"
          EOL

      - name: Build Android APK Debug
        run: |
          ./godot/Godot_v4.5-beta5_linux.x86_64 --headless \
            --export-debug "Android" build/app-debug.apk --verbose

      - name: Build Android APK Release
        env:
          KEYSTORE_PASSWORD: android
          KEY_ALIAS: androiddebugkey
          KEY_PASSWORD: android
        run: |
          ./godot/Godot_v4.5-beta5_linux.x86_64 --headless \
            --export "Android" build/app-release.apk --verbose

      - name: Build Android AAB
        env:
          KEYSTORE_PASSWORD: android
          KEY_ALIAS: androiddebugkey
          KEY_PASSWORD: android
        run: |
          ./godot/Godot_v4.5-beta5_linux.x86_64 --headless \
            --export "Android App Bundle" build/app-release.aab --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: godot-android-build
          path: build/
