name: Build Godot Android Project

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip openjdk-17-jdk zip tar

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Download Godot Engine
        run: |
          GODOT_VERSION="4.5-beta5"
          mkdir -p ~/.godot
          wget https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_linux.x86_64.zip
          unzip Godot_v${GODOT_VERSION}_linux.x86_64.zip -d ~/.godot
          mv ~/.godot/Godot_v${GODOT_VERSION}_linux.x86_64 ~/.godot/godot
          chmod +x ~/.godot/godot

      - name: Install Godot Export Templates
        run: |
          GODOT_VERSION="4.5-beta5"
          TEMPLATES_DIR="$HOME/.local/share/godot/export_templates/4.5.beta5"
          mkdir -p "$TEMPLATES_DIR"
          wget https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_export_templates.tpz
          unzip Godot_v${GODOT_VERSION}_export_templates.tpz -d /tmp/templates
          mkdir -p "$TEMPLATES_DIR"
          mv /tmp/templates/templates/* "$TEMPLATES_DIR/"

      # FIX: Add Android build template installation
      - name: Install Android Build Template
        run: |
          GODOT_VERSION="4.5-beta5"
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}/Godot-v${GODOT_VERSION}-android_build_template.zip
          mkdir -p android/build
          unzip Godot-v${GODOT_VERSION}-android_build_template.zip -d android/build_temp
          mv android/build_temp/android_template/* android/build/
          rm -r android/build_temp

      - name: Android SDK & NDK setup
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux-11076708_latest.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH:$ANDROID_SDK_ROOT/platform-tools

          yes | sdkmanager --licenses > /dev/null || true
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "ndk;25.2.9519653" > /dev/null

      - name: Generate Debug Keystore
        run: |
          keytool -genkeypair -noprompt \
            -keystore debug.keystore \
            -storepass android \
            -alias androiddebugkey \
            -keypass android \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Godot,L=Internet,ST=World,C=US"

      - name: Create export_presets.cfg
        run: |
          cat <<EOL > export_presets.cfg
          [preset.0]
          name="Android"
          platform="Android"
          runnable=true
          export_filter="all_resources"
          include_filter=""
          exclude_filter=""
          export_path=""
          script_export_mode=2
          
          [preset.0.options]
          package/unique_name="com.example.testproject"
          version/code=1
          version/name="1.0"
          gradle_build/use_gradle_build=true
          architectures/arm64-v8a=true
          permissions/internet=true
          permissions/read_external_storage=true
          permissions/write_external_storage=true
          keystore/debug="./debug.keystore"
          keystore/debug_user="androiddebugkey"
          keystore/debug_password="android"
          EOL

      - name: Create build directory
        run: mkdir -p build

      - name: Build Android Debug APK
        run: ~/.godot/godot --headless --export-debug "Android" build/android_debug.apk --verbose

      - name: Build Android Release APK
        run: ~/.godot/godot --headless --export-release "Android" build/android_release.apk --verbose

      - name: Build Android Release AAB
        run: |
          sed -i 's/gradle_build\/export_format=0/gradle_build\/export_format=1/' export_presets.cfg
          ~/.godot/godot --headless --export-release "Android" build/android_release.aab --verbose

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-builds
          path: build/
