name: Build Godot Test Project for Android

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip openjdk-17-jdk zip tar
        
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Godot Engine
        # IMPORTANTE: Mude a URL para a versão exata do seu projeto.
        run: |
          GODOT_VERSION="4.5-beta5"
          mkdir ~/.godot
          wget https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_linux.x86_64.zip
          unzip Godot_v${GODOT_VERSION}_linux.x86_64.zip
          mv Godot_v${GODOT_VERSION}_linux.x86_64 ~/.godot/godot
          chmod +x ~/.godot/godot
          
      - name: Download Godot Export Templates
        # IMPORTANTE: Mude a URL para a versão exata do seu projeto.
        run: |
          GODOT_VERSION="4.5.beta5" # Note o formato diferente para o diretório
          TEMPLATES_DIR="$HOME/.local/share/godot/export_templates/${GODOT_VERSION}"
          mkdir -p "$TEMPLATES_DIR"
          wget https://github.com/godotengine/godot-builds/releases/download/4.5-beta5/Godot_v4.5-beta5_export_templates.tpz
          unzip Godot_v4.5-beta5_export_templates.tpz -d "$TEMPLATES_DIR"
          echo "Templates para a versão ${GODOT_VERSION} instalados."

      - name: Android SDK & NDK Setup
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux-11076708_latest.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

          yes | sdkmanager --licenses > /dev/null || true
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "ndk;25.2.9519653" > /dev/null

      - name: Generate Debug Keystore
        run: |
          keytool -genkeypair -noprompt \
            -keystore debug.keystore \
            -storepass android \
            -alias androiddebugkey \
            -keypass android \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Godot,L=Internet,ST=World,C=US"

      - name: Create export_presets.cfg for Test Project
        # CORREÇÃO: Adicionados os campos que estavam faltando
        run: |
          cat <<EOL > export_presets.cfg
          [preset.0]
          name="Android"
          platform="Android"
          runnable=true
          export_filter="all_resources"
          include_filter=""
          exclude_filter=""
          export_path=""
          script_export_mode=2
          
          [preset.0.options]
          package/unique_name="com.example.testproject"
          version/code=1
          version/name="1.0"
          
          # Configuração para usar Gradle e os templates corretos
          gradle_build/use_gradle_build=true
          custom_template/debug="$HOME/.local/share/godot/export_templates/4.5.beta5/android_debug.apk"
          custom_template/release="$HOME/.local/share/godot/export_templates/4.5.beta5/android_release.apk"
          
          # Arquiteturas
          architectures/arm64-v8a=true
          
          # Permissões essenciais
          permissions/internet=true
          permissions/read_external_storage=true
          permissions/write_external_storage=true
          EOL

      - name: Create Build Directory
        run: mkdir -p build

      - name: Build Android Debug APK
        run: |
          ~/.godot/godot --headless --export-debug "Android" build/android_debug.apk --verbose

      - name: Build Android Release APK
        run: |
          ~/.godot/godot --headless --export-release "Android" build/android_release.apk --verbose
          
      - name: Build Android Release AAB
        run: |
          # A exportação para AAB requer que o formato seja alterado no preset
          sed -i 's/gradle_build\/export_format=0/gradle_build\/export_format=1/' export_presets.cfg
          ~/.godot/godot --headless --export-release "Android" build/android_release.aab --verbose

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-test-build
          path: build/

