name: Build Godot Android

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip openjdk-17-jdk keytool wget

      - name: Download Godot Headless + Export Templates
        run: |
          mkdir -p godot
          wget https://downloads.tuxfamily.org/godotengine/4.5/beta5/Godot_v4.5-beta5_linux.x86_64.zip -O godot/godot.zip
          unzip godot/godot.zip -d godot/
          mv godot/Godot_v4.5-beta5_linux.x86_64 godot/godot
          chmod +x godot/godot
          
          wget https://downloads.tuxfamily.org/godotengine/4.5/beta5/Godot_v4.5-beta5_export_templates.tpz -O godot/templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/4.5.beta5
          unzip godot/templates.tpz -d ~/.local/share/godot/export_templates/4.5.beta5

      - name: Create debug keystore if not exists
        run: |
          if [ ! -f debug.keystore ]; then
            keytool -genkeypair -v \
              -keystore debug.keystore \
              -storepass android \
              -keypass android \
              -alias androiddebugkey \
              -dname "CN=Android Debug,O=Godot,C=NL" \
              -keyalg RSA -keysize 2048 -validity 10000
          fi

      - name: Generate export_presets.cfg
        run: |
          cat > export_presets.cfg << 'EOF'
          [preset.0]
          name="Android Debug"
          platform="Android"
          runnable=true
          custom_features=""
          export_filter="all_resources"
          include_filter=""
          exclude_filter=""
          export_path="build/android-debug.apk"
          encryption_include_filters=""
          encryption_exclude_filters=""
          encrypt_pck=false
          encrypt_directory=false
          custom_template/debug="~/.local/share/godot/export_templates/4.5.beta5/android_debug.apk"
          custom_template/release="~/.local/share/godot/export_templates/4.5.beta5/android_release.apk"

          [preset.1]
          name="Android Release APK"
          platform="Android"
          runnable=false
          custom_features=""
          export_filter="all_resources"
          include_filter=""
          exclude_filter=""
          export_path="build/android-release.apk"
          encryption_include_filters=""
          encryption_exclude_filters=""
          encrypt_pck=false
          encrypt_directory=false
          custom_template/debug="~/.local/share/godot/export_templates/4.5.beta5/android_debug.apk"
          custom_template/release="~/.local/share/godot/export_templates/4.5.beta5/android_release.apk"

          [preset.2]
          name="Android Release AAB"
          platform="Android"
          runnable=false
          custom_features=""
          export_filter="all_resources"
          include_filter=""
          exclude_filter=""
          export_path="build/android-release.aab"
          encryption_include_filters=""
          encryption_exclude_filters=""
          encrypt_pck=false
          encrypt_directory=false
          custom_template/debug="~/.local/share/godot/export_templates/4.5.beta5/android_debug.apk"
          custom_template/release="~/.local/share/godot/export_templates/4.5.beta5/android_release.apk"
          EOF

      - name: Build Android Debug APK
        run: |
          ./godot/godot --headless --export-debug "Android Debug"

      - name: Build Android Release APK
        run: |
          ./godot/godot --headless --export-release "Android Release APK"

      - name: Build Android Release AAB
        run: |
          ./godot/godot --headless --export-release "Android Release AAB"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-builds
          path: build/
