name: Godot 4.5 Beta 5 Android Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip openjdk-11-jdk zip tar

      - name: Download Godot Linux x86_64
        run: |
          mkdir godot
          wget -q https://github.com/godotengine/godot-builds/releases/download/4.5-beta5/Godot_v4.5-beta5_linux.x86_64.zip
          unzip -q Godot_v4.5-beta5_linux.x86_64.zip -d godot
          chmod +x godot/Godot_v4.5-beta5_linux.x86_64

      - name: Download Godot export templates
        run: |
          mkdir -p ~/.local/share/godot/templates/4.5.beta5
          wget -q https://github.com/godotengine/godot-builds/releases/download/4.5-beta5/Godot_v4.5-beta5_export_templates.tpz
          unzip -q Godot_v4.5-beta5_export_templates.tpz -d ~/.local/share/godot/templates/4.5.beta5

      - name: Setup Android SDK & NDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/33.0.2:$PATH

          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses || true

          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "ndk;25.2.9519653"

      - name: Generate debug keystore
        run: |
          keytool -genkeypair -noprompt \
            -keystore debug.keystore \
            -storepass android \
            -alias androiddebugkey \
            -keypass android \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Godot,L=Internet,ST=World,C=US"

      - name: Create export_presets.cfg
        run: |
          cat > export_presets.cfg << 'EOF'
[preset.0]
name="Android Debug APK"
platform="Android"
runnable=true
export_path="build/debug.apk"
script_export_mode=2

[preset.0.options]
package/unique_name="com.lewriner.game"
package/signed=false
architectures/arm64-v8a=true
version/code=1
version/name="0.1"
permissions/custom_permissions=PackedStringArray()
gradle_build/export_format=0

[preset.1]
name="Android Release APK"
platform="Android"
runnable=true
export_path="build/release.apk"
script_export_mode=2

[preset.1.options]
package/unique_name="com.lewriner.game"
package/signed=true
architectures/arm64-v8a=true
version/code=1
version/name="0.1"
permissions/custom_permissions=PackedStringArray()
gradle_build/export_format=0

[preset.2]
name="Android Release AAB"
platform="Android"
runnable=true
export_path="build/release.aab"
script_export_mode=2

[preset.2.options]
package/unique_name="com.lewriner.game"
package/signed=true
architectures/arm64-v8a=true
version/code=1
version/name="0.1"
permissions/custom_permissions=PackedStringArray()
gradle_build/export_format=1
EOF

      - name: Build all Android targets
        run: |
          mkdir -p build
          ./godot/Godot_v4.5-beta5_linux.x86_64 --headless --export "Android Debug APK" build/debug.apk --verbose
          ./godot/Godot_v4.5-beta5_linux.x86_64 --headless --export "Android Release APK" build/release.apk --verbose
          ./godot/Godot_v4.5-beta5_linux.x86_64 --headless --export "Android Release AAB" build/release.aab --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: godot-android-build
          path: build/
